In [2]:
import numpy as np

In [3]:
X_XOR = np.array([[0,0,1], [0,1,1], [1,0,1],[1,1,1]]) 
y_truth = np.array([[0],[1],[1],[0]])

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_der(output):
    return output * (1 - output)

In [5]:
np.random.seed(1)
syn_0 = 2*np.random.random((3,4)) - 1
syn_1 = 2*np.random.random((4,1)) - 1

In [6]:
syn_1

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481],
       [ 0.34093502]])

In [7]:
for i in range(60000):
    layer_1 = sigmoid(X_XOR.dot(syn_0))
    layer_2 = sigmoid(layer_1.dot(syn_1))
    error = layer_2 - y_truth
    layer_2_delta = error * sigmoid_der(layer_2)
    layer_1_error = layer_2_delta.dot(syn_1.T)
    layer_1_delta = layer_1_error * sigmoid_der(layer_1)
    syn_1 -= layer_1.T.dot(layer_2_delta)
    syn_0 -= X_XOR.T.dot(layer_1_delta)
    if i % 10000 == 1:
        print(layer_2)

[[ 0.47070349]
 [ 0.48716227]
 [ 0.54111272]
 [ 0.54275466]]
[[ 0.00702131]
 [ 0.99101058]
 [ 0.99215251]
 [ 0.01047789]]
[[ 0.00473089]
 [ 0.99397288]
 [ 0.99465475]
 [ 0.00705394]]
[[ 0.0037833 ]
 [ 0.9951994 ]
 [ 0.99570207]
 [ 0.00563454]]
[[ 0.00323678]
 [ 0.99590652]
 [ 0.99631031]
 [ 0.0048149 ]]
[[ 0.00287145]
 [ 0.99637884]
 [ 0.99671886]
 [ 0.00426659]]


In [8]:
layer_2_delta

array([[  6.77210834e-06],
       [ -1.07094941e-05],
       [ -8.87110478e-06],
       [  1.49004238e-05]])

In [9]:
sigmoid_der(layer_1)

array([[  1.98837541e-01,   1.02860175e-01,   6.83672492e-02,
          2.88133951e-03],
       [  1.38952969e-01,   3.92835720e-04,   1.63746592e-02,
          9.27268048e-02],
       [  3.75641061e-03,   9.38081354e-02,   2.18142168e-02,
          1.35495307e-01],
       [  4.54798845e-02,   2.42409810e-02,   3.07980841e-05,
          1.02007295e-01]])