In [1]:
import numpy as np

In [2]:
X_XOR = np.array([[0,0,1], [0,1,1], [1,0,1],[1,1,1]]) 
y_truth = np.array([[0],[1],[1],[0]])

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_der(output):
    return output * (1 - output)

In [4]:
np.random.seed(1)
syn_0 = 2*np.random.random((3,4)) - 1
syn_1 = 2*np.random.random((4,1)) - 1

In [5]:
for i in range(1):
    layer_1 = sigmoid(X_XOR.dot(syn_0))
    layer_2 = sigmoid(layer_1.dot(syn_1))
    error = y_truth - layer_2
    layer_2_delta = error * sigmoid_der(layer_2)
    #layer_1_error = layer_2_delta.dot(syn_1.T)
    #layer_1_delta = layer_1_error * sigmoid_der(layer_1)
    #syn_1 += layer_1.dot(layer_2_delta)
   # syn_0 += X_OR.T.dot(layer_1_delta)

In [6]:
layer_1

array([[ 0.44856632,  0.51939863,  0.45968497,  0.59156505],
       [ 0.28639589,  0.32350963,  0.31236398,  0.51538526],
       [ 0.40795614,  0.62674606,  0.23841622,  0.49377636],
       [ 0.25371248,  0.42628115,  0.14321233,  0.41732254]])

In [7]:
#layer_1_delta

In [8]:
#sigmoid(3.1)

In [9]:
layer_2

array([[ 0.47372957],
       [ 0.48895696],
       [ 0.54384086],
       [ 0.54470837]])

In [10]:
error

array([[-0.47372957],
       [ 0.51104304],
       [ 0.45615914],
       [-0.54470837]])

In [11]:
sigmoid_der(layer_2)

array([[ 0.24930986],
       [ 0.24987805],
       [ 0.24807798],
       [ 0.24800116]])

In [12]:
layer_2_delta

array([[-0.11810546],
       [ 0.12769844],
       [ 0.11316304],
       [-0.13508831]])